### ISSUE TITLE
undefined method `images' for #<DockerCloud::Client:0x00...>

### ISSUE THREAD

**Issue by zedtux** [jntullo/ruby-docker-cloud#21]
It looks like the [`image` method from the `Service` class](https://github.com/jntullo/ruby-docker-cloud/blob/master/lib/docker_cloud/service.rb#L9) is not working:

```ruby
irb(main):009:0> stack.services.first.image
NoMethodError: undefined method `images' for #<DockerCloud::Client:0x007f78f1522508>
	from /bundle/gems/docker_cloud-0.3.0/lib/docker_cloud/service.rb:10:in `image'
	from (irb):9
	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /bundle/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by zedtux** [comment]
Apparently, repo no more maintained ... closing the issue.
